# Generated by Django 4.1 on 2022-09-01 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('lab_validation', models.BooleanField(default=False)),
                ('videoconference', models.BooleanField(verbose_name='is possible videoconference')),
                ('television_screen', models.BooleanField()),
                ('projector', models.BooleanField()),
                ('paperboard', models.BooleanField()),
                ('whiteboard', models.BooleanField()),
                ('wall_whiteboard', models.BooleanField()),
                ('computer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_timestamps', models.DateTimeField()),
                ('duration', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=200)),
                ('physically_present_person', models.IntegerField()),
                ('other_persons', models.CharField(max_length=300)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_meeting_room.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_meeting_room.user')),
            ],
        ),
    ]
