# Generated by Django 4.1 on 2022-09-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_meeting_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='other_persons',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='physically_present_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
